<?php

define("TEAM_NAME_MAX_LENGTH", 32);
define("TEAM_NAME_MIN_LENGTH", 4);
define("TEAM_BIO_MAX_LENGTH", 250);
define("TEAM_BIO_MIN_LENGTH", 1);
define("TEAM_USERPAGE_MAX_LENGTH", 5000);
define("TEAM_USERPAGE_MIN_LENGTH", 1);
define("TEAM_AVATAR_MAX_WIDTH", 512);
define("TEAM_AVATAR_MAX_HEIGHT", 512);
define("TEAM_BANNER_MAX_WIDTH", 1100);
define("TEAM_BANNER_MAX_HEIGHT", 300);